import sunny from "../assets/4804-weather-sunny.json";
import cloudy from "../assets/4800-weather-partly-cloudy.json";
import foggy from "../assets/4791-foggy.json";
import windy from "../assets/4806-weather-windy.json";
import mist from "../assets/4795-weather-mist.json";
import storm from "../assets/4803-weather-storm.json";
import shower from "../assets/4801-weather-partly-shower.json";
import stormshowersday from "../assets/4792-weather-stormshowersday.json";
export const weatherIcon: Record<number, any> = {
  1: sunny,
  2: cloudy,
  3: cloudy,
  4: cloudy,
  5: foggy,
  6: foggy,
  7: windy,
  8: mist,
  9: mist,
  11: mist,
  12: storm,
  13: shower,
  14: shower,
  15: storm,
  16: storm,
  17: stormshowersday,
  18: storm,
  19: windy,
  20: foggy,
  21: foggy,
  // 22: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 23: 'https://assets10.lottiefiles.com/temp/lf20_BSVgyt.json',
  // 24: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 25: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 26: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 27: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 29: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',

  33: sunny,
  34: cloudy,
  35: cloudy,
  36: cloudy,
  37: foggy,
  38: foggy,
  39: windy,
  40: mist,
  41: mist,
  42: mist,
  43: storm,
  44: shower,
  // 14: 'https://assets10.lottiefiles.com/temp/lf20_rpC1Rd.json',
  // 15: 'https://assets10.lottiefiles.com/temp/lf20_XkF78Y.json',
  // 16: 'https://assets10.lottiefiles.com/temp/lf20_XkF78Y.json',
  // 17: 'https://assets10.lottiefiles.com/temp/lf20_JA7Fsb.json',
  // 18: 'https://assets10.lottiefiles.com/temp/lf20_XkF78Y.json',
  // 19: require('../assets/4806-weather-windy.json'),
  // 20: 'https://assets10.lottiefiles.com/temp/lf20_HflU56.json',
  // 21: 'https://assets10.lottiefiles.com/temp/lf20_HflU56.json',
  // 22: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 23: 'https://assets10.lottiefiles.com/temp/lf20_BSVgyt.json',
  // 24: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 25: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 26: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 27: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
  // 29: 'https://assets10.lottiefiles.com/temp/lf20_WtPCZs.json',
};
